<?php
/* Nouvelle Donne -- Copyright (C) Perrick Penet-Avez 2014 - 2014 */

$array_month[0] = "--";
$array_month[1] = "janvier";
$array_month[2] = "février";
$array_month[3] = "mars";
$array_month[4] = "avril";
$array_month[5] = "mai";
$array_month[6] = "juin";
$array_month[7] = "juillet";
$array_month[8] = "août";
$array_month[9] = "septembre";
$array_month[10] = "octobre";
$array_month[11] = "novembre";
$array_month[12] = "décembre";

$array_week[0] = "Dimanche";
$array_week[1] = "Lundi";
$array_week[2] = "Mardi";
$array_week[3] = "Mercredi";
$array_week[4] = "Jeudi";
$array_week[5] = "Vendredi";
$array_week[6] = "Samedi";
$array_week[7] = "Dimanche";

$__['--'] = "--";
$__['%s : %s votes'] = "%s: %s votes";
$__['A comity'] = "Un comité";
$__['A consultation is currently open: <strong>%s</strong>.'] = "Une consultation est actuellement en cours : <strong>%s</strong>";
$__['add OK'] = "ajout OK";
$__['adds OK'] = "ajouts OK";
$__['Administration: %s'] = "Administration : %s";
$__['Agree with this vote'] = "Approuver ce vote";
$__['All members'] = "Tous les adhérents";
$__['answer'] = "réponse";
$__['Answers = %s'] = "Réponses = %s";
$__['Answers\' hashes = %s'] = "Clés de hashage des réponses = %s";
$__['Choice n°%s'] = "Choix n°%s";
$__['Choices'] = "Choix";
$__['Choices = %s'] = "Choix = %s";
$__['Choices * Votes = %s'] = "Choix * Votes = %s";
$__['Comity'] = "Comité";
$__['Consult this consultation\'s results'] = "Consulter les résultats de cette consultation";
$__['consultation'] = "consultation";
$__['Consultation\'s hashes'] = "Clés de hashage de la consultation";
$__['Consultation\'s hash = %s'] = "Clé de hashage de la consultation = %s";
$__['Consultations\' tool'] = "Outil de consultations";
$__['Consultation\'s convocation: %s'] = "Convocation à la consultation : %s";
$__['Create a new consultation'] = "Créer une nouvelle consultation";
$__['delete'] = "supprimer";
$__['deletion OK'] = "suppression OK";
$__['deletions OK'] = "suppressions OK";
$__['Description'] = "Description";
$__['Edit the consultation \'%s\''] = "Editer la consultation '%s'";
$__['Edit this consultation'] = "Editer cette consultation";
$__['Email'] = "Email";
$__['Emails'] = "Emails";
$__['For example: \'php bot.php --send_convocations consultation=X\' (where X is the ID of the consultation).'] = "Par exemple : 'php bot.php --send_convocations consultation=X' (où X correspond à l'ID de la consultation).";
$__['Hello %s,'] = "Bonjour %s,";
$__['If you want to change your answers, you can still change them.'] = "Si vous le souhaitez, vous pouvez encore changer votre vote.";
$__['In order to send all the convocations in one batch, you\'ll need to execute this command: \'php bot.php --send_convocations consultation=%s\'.'] = "Pour envoyer toutes les convocations d'un coup, vous aurez besoin d'exécuter cette commande : 'php bot.php --send_convocations consultation=%s'.";
$__['Let\'s vote'] = "Place au vote";
$__['Let\'s see if you can vote'] = "Voyons s'il y a des votes en cours";
$__['mask'] = "masquer";
$__['member'] = "membre";
$__['member / comity'] = "membre / comité";
$__['Methods available with %s:'] = "Méthodes disponibles avec %s :";
$__['Move back to vote'] = "Revenir sur le vote";
$__['Move on to opinions'] = "Passer aux avis";
$__['Move on to vote'] = "Passer au vote";
$__['Name'] = "Nom";
$__['New consultation'] = "Nouvelle consultation";
$__['No'] = "Non";
$__['No consultation is currently open.'] = "Aucune consultation n'est ouverte pour le moment";
$__['nothing to do'] = "rien à faire";
$__['Number of votes & answers'] = "Nombre de votes et de réponses";
$__['Opinions : list of views'] = "Opinions : liste d'avis";
$__['Page missing'] = "Page manquante";
$__['Please use the link below to vote about "%s":'] = "Merci d'utiliser le lien ci-dessous pour procéder au vote sur \"%s\" :";
$__['Position %s: %s with %s points'] = "Position #%s : %s avec %s points";
$__['Preambule : list of facts'] = "Préambule : liste de documents factuels";
$__['Presentation'] = "Présentation";
$__['Procedure details'] = "Détails de la procédure";
$__['Period'] = "Période";
$__['Question'] = "Question";
$__['Results'] = "Résultats";
$__['Results with Broda\'s method'] = "Résultats avec la méthode de Broda";
$__['Results with Condorcet\'s method'] = "Résultats avec la méthode de Condorcet";
$__['save'] = "sauvegarder";
$__['Save'] = "Sauvegarder";
$__['seems OK'] = "semble OK";
$__['Show the consultation \'%s\''] = "Afficher la consultation '%s'";
$__['Show the results for the consultation \'%s\''] = "Afficher les résultats de la consultation '%s'";
$__['Show the verifications for the consultation \'%s\''] = "Afficher les vérifications de la consultation '%s'";
$__['Some departement numbers'] = "Des codes départementaux (de 2 caractères)";
$__['Some emails'] = "Des emails";
$__['Sorry, no consultation is currently accessible to you.'] = "Désolé, aucune consultation ne vous est accessible en ce moment.";
$__['Sorry, there was an error while sending your convocation by email.'] = "Désolé, il y a eu une erreur à l'envoi de votre convocation par email.";
$__['Sorry, your convocation is missing.'] = "Désolé, votre convocation est manquante.";
$__['Sorry, your convocation is not valid.'] = "Désolé, votre convocation n'est pas valide.";
$__['Sorry, your email is not valid.'] = "Désolé, votre email n'est pas valable."; 
$__['Start'] = "Début";
$__['Stop'] = "Fin";
$__['Summary'] = "Récapitulatif";
$__['Thank you for voting.'] = "Merci d'avoir voté.";
$__['The consultations team'] = "L'équipe des consultations";
$__['The creation of a new consultation is only possible by an administrator. If you want to create one, you can <a href="mailto:%s">contact them by email</a>.'] = "La création d'une nouvelle consultation est réservé aux administrateurs. Si vous souhaitez en créer une, vous pouvez <a href=\"mailto:%s\">les contacter par email</a>.";
$__['The hashes for this consultation, these votes and these answers are troublesome: you should not validate the results.'] = "Les clés de hashage pour cette consultation avec ces votes et ces réponses posent problème : vous ne devriez pas valider ces résultats.";
$__['The number of answers is different from the number of choices times the number of votes: you should not validate the results.'] = "Le nombre de réponses est différent du nombre de choix fois le nombre de votes : vous ne devriez pas valider ces résultats.";
$__['This consultation has already started.'] = "Cette consultation a d'ores et déjà commencé";
$__['This consultation is already closed.'] = "Cette consultation est d'ores et déjà fermée";
$__['This consultation is already open.'] = "Cette consultation est d'ores et déjà ouverte";
$__['This consultation is not closed yet.'] = "Cette consultation n'est pas encore fermée";
$__['This consultation will be closed definitely on %s.'] = "Cette consultation sera close définitivement le %s";
$__['Title'] = "Titre";
$__['update'] = "mise à jour";
$__['update OK'] = "mise à jour OK";
$__['URL'] = "URL";
$__['Verifications'] = "Vérifications";
$__['Verify'] = "Vérifier";
$__['Verify your current convocations'] = "Vérifier vos convocations du moment";
$__['vote'] = "vote";
$__['Vote'] = "Voter";
$__['Voters'] = "Votants";
$__['Votes = %s'] = "Votes = %s";
$__['Votes\' hashes = %s'] = "Clés de hashage des votes = %s";
$__['Yes'] = "Oui";
$__['Your answers are not coherent. Please make sure you\'re ranking all the possibles choices.'] = "Vos choix ne sont pas cohérents. Merci de bien vouloir classer tous les choix possibles.";
$__['Your answers were found : you\'ll find them below.'] = "Vos choix ont bien été enregistrés : vous les retrouverez ci-dessous.";
$__['Your answers were not found. Please vote first.'] = "Vos choix n'ont pas été trouvés. Merci de bien vouloir commencer par voter.";
$__['Your answers were not saved. Please contact the technical team : %s.'] = "Vos choix n'ont pas été sauvegardés. Merci de bien vouloir contacter l'équipe technique : %s";
$__['Your convocation(s) have been sent : please check your emails in order to proceed to the vote.'] = "Votre (ou vos) convocation a bien été envoyée : merci de consulter vos emails afin de procéder au vote.";
$__['Your vote has already been registered on <strong>%s</strong>. If you try to re-vote, it will simply replace the preceding one.'] = "Votre vote a déjà été pris en compte le <strong>%s</strong>. Si vous re-votez, le précédent sera simplement remplacé.";
