<?php
/* Nouvelle Donne -- Copyright (C) Perrick Penet-Avez 2014 - 2014 */

$array_month[0] = "--";
$array_month[1] = "janvier";
$array_month[2] = "février";
$array_month[3] = "mars";
$array_month[4] = "avril";
$array_month[5] = "mai";
$array_month[6] = "juin";
$array_month[7] = "juillet";
$array_month[8] = "août";
$array_month[9] = "septembre";
$array_month[10] = "octobre";
$array_month[11] = "novembre";
$array_month[12] = "décembre";

$array_week[0] = "Dimanche";
$array_week[1] = "Lundi";
$array_week[2] = "Mardi";
$array_week[3] = "Mercredi";
$array_week[4] = "Jeudi";
$array_week[5] = "Vendredi";
$array_week[6] = "Samedi";
$array_week[7] = "Dimanche";

$__['--'] = "--";
$__['A consultation is currently open: <strong>%s</strong>.'] = "Une consultation est actuellement en cours : <strong>%s</strong>";
$__['add OK'] = "ajout OK";
$__['adds OK'] = "ajouts OK";
$__['Agree with this vote'] = "Approuver ce vote";
$__['answer'] = "réponse";
$__['Choice n°%s'] = "Choix n°%s";
$__['delete'] = "supprimer";
$__['deletion OK'] = "suppression OK";
$__['deletions OK'] = "suppressions OK";
$__['If you want to change your answers, you can still change them.'] = "Si vous le souhaitez, vous pouvez encore changer votre vote.";
$__['Let\'s vote'] = "Place au vote";
$__['Move back to vote'] = "Revenir sur le vote";
$__['Move on to opinions'] = "Passer aux avis";
$__['Move on to vote'] = "Passer au vote";
$__['No consultation is currently open.'] = "Aucune consultation n'est ouverte pour le moment.";
$__['Preambule : list of facts'] = "Préambule : liste de documents factuels";
$__['Procedure details'] = "Détails de la procédure";
$__['Opinions : list of views'] = "Opinions : liste d'avis";
$__['save'] = "sauvegarder";
$__['seems OK'] = "semble OK";
$__['Summary'] = "Récapitulatif";
$__['Thank you for voting.'] = "Merci d'avoir voté.";
$__['This consultation will be closed definitely on %s.'] = "Cette consultation sera close définitivement le %s.";
$__['update'] = "mise à jour";
$__['update OK'] = "mise à jour OK";
$__['vote'] = "vote";
$__['Vote'] = "Voter";
$__['Your answers are not coherent. Please make sure you\'re ranking all the possibles choices.'] = "Vos choix ne sont pas cohérents. Merci de bien vouloir classer tous les choix possibles.";
$__['Your answers were found : you\'ll find them below.'] = "Vos choix ont bien été retrouvés : vous les retrouverez ci-dessous.";
$__['Your answers were not found. Please vote first.'] = "Vos choix n'ont pas été trouvés. Merci de bien vouloir commencer par voter.";
$__['Your answers were not saved. Please contact the technical team : tech@nouvelledonne.fr.'] = "Vos choix n'ont pas été sauvegardés. Merci de bien vouloir contacter l'équipe technique : tech@nouvelledonne.fr";
$__['Your vote has already been registered on <strong>%s</strong>.'] = "Votre vote a déjà été pris en compte le <strong>%s</strong>.";
